---
name: Math-Expression-Evaluator
version: 0.1.2
author:
  - Moritz Lenz
abstract: 'parses, compiles and evaluates mathematic expressions'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Data::Dumper: 0
  Math::Trig: 0
  perl: 5.006001
provides:
  Math::Expression::Evaluator:
    file: lib/Math/Expression/Evaluator.pm
    version: 0.1.2
  Math::Expression::Evaluator::Lexer:
    file: lib/Math/Expression/Evaluator/Lexer.pm
  Math::Expression::Evaluator::Optimizer:
    file: lib/Math/Expression/Evaluator/Optimizer.pm
  Math::Expression::Evaluator::Parser:
    file: lib/Math/Expression/Evaluator/Parser.pm
  Math::Expression::Evaluator::Util:
    file: lib/Math/Expression/Evaluator/Util.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
