---
name: Math-Expression-Evaluator
version: 0.0.6
author:
  - Moritz Lenz
abstract: ~
license: perl
requires:
  Carp: 0
  Data::Dumper: 0
  Math::Trig: 0
  perl: 5.6.1
provides:
  Math::Expression::Evaluator:
    file: lib/Math/Expression/Evaluator.pm
    version: 0.0.6
generated_by: Module::Build version 0.26
